// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVTTkSa-OL-NX5VeD7UCSm9WgwmOMiMcw',
    appId: '1:1054777731423:web:e88208d4be0ed6001eeeea',
    messagingSenderId: '1054777731423',
    projectId: 'speedwaystore-c0aa9',
    authDomain: 'speedwaystore-c0aa9.firebaseapp.com',
    storageBucket: 'speedwaystore-c0aa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzgiLaW8eN5uA9WPYXWvwG6-NWVWoa_ys',
    appId: '1:1054777731423:android:c24f83c47f293f521eeeea',
    messagingSenderId: '1054777731423',
    projectId: 'speedwaystore-c0aa9',
    storageBucket: 'speedwaystore-c0aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79pLho4uKr0w2WxCrCaVrQZtWPOzNqGQ',
    appId: '1:1054777731423:ios:60c68a3ba0cb7c851eeeea',
    messagingSenderId: '1054777731423',
    projectId: 'speedwaystore-c0aa9',
    storageBucket: 'speedwaystore-c0aa9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC79pLho4uKr0w2WxCrCaVrQZtWPOzNqGQ',
    appId: '1:1054777731423:ios:60c68a3ba0cb7c851eeeea',
    messagingSenderId: '1054777731423',
    projectId: 'speedwaystore-c0aa9',
    storageBucket: 'speedwaystore-c0aa9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVTTkSa-OL-NX5VeD7UCSm9WgwmOMiMcw',
    appId: '1:1054777731423:web:7abda550fa78a3601eeeea',
    messagingSenderId: '1054777731423',
    projectId: 'speedwaystore-c0aa9',
    authDomain: 'speedwaystore-c0aa9.firebaseapp.com',
    storageBucket: 'speedwaystore-c0aa9.firebasestorage.app',
  );
}
